# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100)),
                ('name', models.CharField(default='', max_length=200)),
                ('adress', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=200)),
            ],
        ),
    ]
