# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='condition',
            field=models.CharField(default='CO', max_length=2),
        ),
    ]
